export const DEFAULT_PROJECT_TASKS = [
  { name: "Layout building pad", phase: "sitework", sort_order: 10 },
  { name: "Excavate footings", phase: "foundation", sort_order: 20 },
  { name: "Place footing rebar", phase: "foundation", sort_order: 30 },
  { name: "Form footings", phase: "foundation", sort_order: 40 },
  { name: "Pour footings", phase: "foundation", sort_order: 50 },
  { name: "Form stem walls", phase: "foundation", sort_order: 60 },
  { name: "Place stem wall rebar", phase: "foundation", sort_order: 70 },
  { name: "Pour stem walls", phase: "foundation", sort_order: 80 },
  { name: "Start framing", phase: "framing", sort_order: 90 },
  { name: "Roof framing", phase: "framing", sort_order: 100 },
  { name: "Install roofing", phase: "roofing", sort_order: 110 },
  { name: "Install windows and exterior doors", phase: "exterior", sort_order: 120 },
  { name: "Rough plumbing", phase: "rough_in", sort_order: 130 },
  { name: "Rough electrical", phase: "rough_in", sort_order: 140 },
  { name: "Rough HVAC", phase: "rough_in", sort_order: 150 },
  { name: "Install insulation", phase: "insulation", sort_order: 160 },
  { name: "Hang drywall", phase: "drywall", sort_order: 170 },
  { name: "Finish drywall", phase: "drywall", sort_order: 180 },
  { name: "Interior paint", phase: "interior_finish", sort_order: 190 },
  { name: "Install cabinets", phase: "cabinetry", sort_order: 200 },
  { name: "Attach cabinet hardware", phase: "cabinetry", sort_order: 210 },
  { name: "Install flooring", phase: "flooring", sort_order: 220 },
  { name: "Punch list", phase: "punch_list", sort_order: 230 },
]

